use crate::curve::CurveAnalysis;
use chrono::Local;
use std::fs;
use std::io::Write;

/// Markdown exporter for mana curve analysis reports
pub struct CurveReportExporter;

impl CurveReportExporter {
    /// Export curve analysis to a markdown file
    pub fn export(analysis: &CurveAnalysis, path: &str) -> Result<(), Box<dyn std::error::Error>> {
        let content = Self::generate(analysis);
        let mut file = fs::File::create(path)?;
        file.write_all(content.as_bytes())?;
        Ok(())
    }

    /// Generate markdown report as a string
    pub fn generate(analysis: &CurveAnalysis) -> String {
        let mut output = String::new();

        // Header
        output.push_str("# Scry Mana Curve Analysis\n\n");
        output.push_str(&format!(
            "Generated: {}\n\n",
            Local::now().format("%Y-%m-%d %H:%M")
        ));

        // Deck info
        if let Some(name) = &analysis.deck_name {
            output.push_str(&format!("**Deck**: {name}\n"));
        }
        if let Some(format) = &analysis.deck_format {
            output.push_str(&format!("**Format**: {format}\n"));
        }
        output.push_str(&format!("**Total Cards**: {}\n", analysis.total_cards));
        output.push_str(&format!("**Unique Cards**: {}\n\n", analysis.unique_cards));

        // Statistics
        output.push_str("## Statistics\n\n");
        output.push_str(&format!(
            "- **Average CMC**: {:.2}\n",
            analysis.stats.average_cmc
        ));
        output.push_str(&format!(
            "- **Median CMC**: {:.1}\n",
            analysis.stats.median_cmc
        ));
        output.push_str(&format!("- **Mode CMC**: {}\n", analysis.stats.mode_cmc));
        output.push_str(&format!(
            "- **Non-land Cards**: {}\n",
            analysis.stats.total_nonland_cards
        ));
        output.push_str(&format!(
            "- **Creatures**: {} ({:.1}%)\n",
            analysis.stats.total_creatures,
            if analysis.stats.total_nonland_cards > 0 {
                analysis.stats.total_creatures as f64 / analysis.stats.total_nonland_cards as f64
                    * 100.0
            } else {
                0.0
            }
        ));
        output.push_str(&format!(
            "- **Non-creatures**: {} ({:.1}%)\n\n",
            analysis.stats.total_non_creatures,
            if analysis.stats.total_nonland_cards > 0 {
                analysis.stats.total_non_creatures as f64
                    / analysis.stats.total_nonland_cards as f64
                    * 100.0
            } else {
                0.0
            }
        ));

        // Distribution table
        if !analysis.buckets.is_empty() {
            output.push_str("## Distribution by CMC\n\n");
            output.push_str("| CMC | Total | Creatures | Non-creatures | Percent |\n");
            output.push_str("|-----|-------|-----------|---------------|--------|\n");

            for bucket in &analysis.buckets {
                let pct = analysis
                    .stats
                    .cmc_distribution
                    .get(&bucket.cmc)
                    .copied()
                    .unwrap_or(0.0)
                    * 100.0;
                output.push_str(&format!(
                    "| {} | {} | {} | {} | {:.1}% |\n",
                    bucket.cmc,
                    bucket.total_count,
                    bucket.creature_count,
                    bucket.non_creature_count,
                    pct
                ));
            }
            output.push('\n');

            // Card lists by CMC
            output.push_str("## Cards by CMC\n\n");
            for bucket in &analysis.buckets {
                output.push_str(&format!("### {} CMC\n\n", bucket.cmc));

                if !bucket.creature_names.is_empty() {
                    output.push_str("**Creatures:**\n");
                    for name in &bucket.creature_names {
                        output.push_str(&format!("- {name}\n"));
                    }
                    output.push('\n');
                }

                if !bucket.non_creature_names.is_empty() {
                    output.push_str("**Non-creatures:**\n");
                    for name in &bucket.non_creature_names {
                        output.push_str(&format!("- {name}\n"));
                    }
                    output.push('\n');
                }
            }
        }

        // Footer
        output.push_str("---\n\n");
        output.push_str("*Generated by scry mana curve analyzer*\n");

        output
    }
}
